### ISSUE TITLE
您好,我想问一下 模型压缩-剪枝算法详解中, 权重高斯分布统计图是 统计所有权重还是只统计了一个卷积核

### ISSUE THREAD

**Issue by Nidhogn** [harleyszhang/dl_note#2]
我试着统计了所有权重 ,0附近的简直高到离谱

**Comment by Nidhogn** [comment]
@HarleysZhang 感觉做出来的图没有您的好看
![Snipaste_2023-04-19_10-52-49](https://user-images.githubusercontent.com/58657378/232954607-231493e3-5751-48c0-b54a-261b1cb26936.jpg)

**Comment by huahai2022** [comment]
感觉差不多，稀疏度高再训练一下，cheems

**Comment by harleyszhang** [comment]
这个时间隔的有点久不记得了，可以去看 AI-EDU 的课程资料。
