### ISSUE TITLE
大佬能解释下ncnn layer里的pipeline是什么作用吗？

### ISSUE THREAD

**Issue by alwensong** [harleyszhang/dl_note#4]

**Comment by harleyszhang** [comment]
不好意思啊，有段时间没用 ncnn 呢。

主要作用是优化性能：

- 通过预先创建和复用 Pipeline，ncnn 可以减少在推理过程中动态创建资源的开销。
- Pipeline 的缓存机制使得同一类型的计算可以重复使用已创建的 Pipeline，进一步提升效率。
